blank_issues_enabled: true
contact_links:
  - name: General question
    url: https://github.com/krwg/blip/discussions
    about: Ask the community (discussions) if you are unsure whether this is a bug.
